### ISSUE TITLE
An option to make glfw optional would be cool

### ISSUE THREAD

**Issue by mgerhardy** [fungos/fips-turbobadger#3]
... I'm using my own SDL2 backend and don't need glfw - and it might produce errors if you include the gl stuff via SDL2 and glfw

**Comment by fungos** [comment]
I think glfw is only required for the demo, is the demo causing the problem? I can add something to disable building the demo, but the clean way will require this feature https://github.com/floooh/fips/issues/69

**Comment by fungos** [comment]
Fixed, can you try it and see if it is ok for you?

**Comment by mgerhardy** [comment]
It now doesn't build anymore.

CMake Error at /home/mgerhardy/dev/fips/cmake/fips.cmake:275 (add_library):
  Cannot find source file:

```
glfw/include/GLFW/glfw3.h
```

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  /home/mgerhardy/dev/fips-glfw/CMakeLists.txt:50 (fips_end_lib)

**Comment by fungos** [comment]
I've created a project that imports turbobadger and with fips config I could disable samples and enable rtti. The glfw got included in the imports anyway due the reference on fips.yml, but the demo wasn't built and nothings referenced the glfw. All this I've done in windows.

I've not tested on linux yet, this error you're getting is on linux?

**Comment by mgerhardy** [comment]
Looks like this is fixed now - mystery fix - maybe cmake didn't notice the updated projects CMakeLists.txt and didn't regnerate the makefiles... (just guessing)

**Comment by fungos** [comment]
To be sure, I've removed the TB_DISABLE_SAMPLES and make use of FIPS_IMPORT. This is safer and way better.
