### ISSUE TITLE
Update turbobadger submodule to contain latest OSX fix

### ISSUE THREAD

**Issue by floooh** [fungos/fips-turbobadger#6]
Currently the turbobadger submodule is pinned to an older version and the latest OSX fix isn't included.

A 'git pull' and 'git checkout master' to reattach to head from within the turbobadger directory, and then 'git commit -a' from fips-turbobadger should do the trick :)

**Comment by fungos** [comment]
Thanks, I'd no access to do this on the phone and then forgot to do it afterwards. :)
