### ISSUE TITLE
dl is missing for linux with glfw and turbobadger demo

### ISSUE THREAD

**Issue by mgerhardy** [fungos/fips-turbobadger#8]
${CMAKE_DL_LIBS} should be added to the linux link libs to fix the unresolved symbols that occur with fips-glfw in combination with some vulkan stuff.

**Comment by mgerhardy** [comment]
https://github.com/floooh/fips-glfw/pull/4

**Comment by fungos** [comment]
Sorry missed this one. Does it is still an issue?

**Comment by mgerhardy** [comment]
nope. already fixed in fips-glfw. sorry for the spam
